version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
# For dagger-compiler annotation processor.
- package-ecosystem: maven
  directory: "/advanced-achievements-plugin"
  schedule:
    interval: weekly
